# -*- coding: utf-8 -*-
"""3d-Data-Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E7wwil5QC2IMGwttUV_UWRi2IsY7l5VO

#3D Data visualization using Matplotlib 
**just give "projection=3d"**
 
 
**Importing the Module**
```
from mpl_toolkits import mplot3d
```
"""

# Commented out IPython magic to ensure Python compatibility.
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline

"""#Assigning Values to draw a rough graph"""

fig = plt.figure(figsize=(14,12))
ax = plt.axes(projection = "3d")

"""# Plotting Lines and values on graph"""

fig = plt.figure(figsize=(14,12))
ax = plt.axes(projection = "3d")
zline = np.linspace(0,15,100)
xline = np.sin(zline)
yline = np.cos(zline)
ax.plot3D(xline,yline,zline,'grey')
zdata = 15 * np.random.random(100)
xdata = np.sin(zdata) + 0.5 * np.random.randn(100)
ydata = np.cos(zdata) + 0.5 * np.random.randn(100)
ax.scatter3D(xdata,ydata,zdata, c = zdata, cmap = 'Greens');

"""# 3D Contour Plot"""

def f(x,y):
  return np.sin(np.sqrt(x ** 2 + y ** 2))

x = np.linspace(-6,6,30)
y = np.linspace(-6,6,30)

X,Y = np.meshgrid(x,y)
Z = f(X,Y)
fig = plt.figure(figsize=(14,12))
ax = plt.axes(projection = "3d")
ax.contour3D(X,Y,Z,50,cmap= 'binary')
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

"""# Surface Triangulation"""

fig = plt.figure(figsize=(14,12))
theta = 2 * np.pi * np.random.random(1000)
r = 6 * np.random.random(1000)
x = np.ravel(r * np.sin(theta))
y = np.ravel(r * np.cos(theta))
z = f(x,y)
ax = plt.axes(projection='3d')
ax.plot_trisurf(x,y,z,cmap = 'plasma',edgecolor='none');